from app.models import RoomName, RoomType
from ._conf import ModelData

_DATAS = {
    ("Single Room", 2): [
        "Deluxe Single Room",
        "Deluxe Single Room with balcony",
        "Deluxe Single Room with beachfront",
        "Budget Single Room",
        "Spacious Single Room",
        "Single Room - Disability Access",
        "Standard Single Room with a balcony",
        "Standard Single Room with garden view",
        "Standard Single Room with lake view",
        "Standard Single Room with mountain view",
        "Standard Single Room with park view",
        "Standard Single Room with swimming pool view",
        "Single Room with Private External Bathroom",
        "Single Room with Shared Bathroom",
        "Single Room with Shared Toilet",
        "Standard Single Room with a terrace",
        "Standard Single Room",
        "Superior Single Room",
        "Superior single room with lake view",
        "Small single room",
        "Single Room without windows",
        "Superior Single Room with a double bed",
        "9-bed Shared room",
    ],
    ("Quadruple", 4): [
        "Comfort Quadruple Room",
        "Deluxe Quadruple Room",
        "Budget Quadruple Room",
        "Premium Quadruple Room",
        "Quadruple Room - Disability Access",
        "Standard Quadruple Room with a balcony",
        "Quadruple Room with a shared bathroom",
        "Standard Quadruple room with garden view",
        "Standard Quadruple room with lake view",
        "Standard Quadruple Room with mountain view",
        "Superior Quadruple Room",
        "Quadruple Room with a terrace",
        "Standard Quadruple Room",
    ],
    ("Family room", 6): [
        "Deluxe Family Room",
        "Family Double Room",
        "Family Room - Disability Access",
        "Family Room with a balcony",
        "Family Room with garden view",
        "Family Room with lake view",
        "Family Room with mountain view",
        "Family Room with a shared bathroom",
        "Family Room with a terrace",
        "Superior Family Room",
        "Family 2-room rooms",
        "Family room with a balcony (1st floor)",
        "Family room with balcony (2nd floor)",
        "Russian complex",
        "Euro complex",
        "Family complex",
        "Family Room (2 Adults + 1 Child)",
        "Sport Complex",
        "Family Room",
    ],
    ("Apartments", 9): [
        "Apartment",
        "Apartment - First Floor",
        "Duplex apartment",
        "Apartment with Balcony",
        "Apartment with lake view",
        "Apartment with mountain view",
        "Apartment with swimming pool view",
        "Apartment with a shared bathroom",
        "Apartment with a terrace",
        "Deluxe Apartment",
        "One-Bedroom Apartment",
        "Studio Apartment",
        "Superior Apartment",
        "Superior Apartment with sauna",
        "Three-Bedroom Apartment",
        "Two-Bedroom Apartment",
        "VIP Apartments",
        "Five-Bedroom Apartment",
        "Duplex Suite apartment",
    ],
    ("Shared room", 10): [
        "A bed in 10-Bed Mixed Shared Room",
        "A bed in 4-Bed Mixed Shared Room",
        "10-bed Shared room",
        "A bed in 6-Bed Shared Room",
        "A bed in 6-Bed Male Shared Room",
        "A bed in 6-Bed Female Shared Room",
        "A bed in 8-Bed Shared Room",
        "A bed in 8-Bed Mixed Shared Room",
        "Bunk Bed in Female Shared Room",
        "Bunk Bed in Male Shared Room",
        "Bunk Bed in Mixed Shared Room",
        "Single Bed in 10-Bed Shared Room",
        "Single Bed in 4-Bed Shared Room",
        "Single Bed in 6-Bed Shared Room",
        "Single Bed in Joint Shared Room",
        "Single Bed in Shared Room",
        "Single Bed in Female Shared Room",
        "Single Bed in Male Shared Room",
        "Shared quintuple room",
        "Shared Six tuple room",
        "Single Bed in Shared Twin Room",
        "Single Bed in Shared Triple Room",
        "Single Bed in 12-Bed Shared Room",
        "Single Bed in 20-Bed Shared Room",
        "Capsule",
        "12-bed shared room",
        "16-bed shared room",
        "Single Bed in Shared Quadruple Room",
        "Single Bed in Shared Quintuple Room",
        "10-bed shared room for men.",
        "8-bed shared room for women.",
        "7-bed Shared room",

    ],
    ("Double room", 4): [
        "Double Room with park view",
        "Deluxe Double Room (for 1 adult and 2 children)",
        "Small Double Room",
        "Deluxe Double Room",
        "Business Class Double Room with Gym Access",
        "Deluxe Double Room + Extra Bed",
        "Deluxe Double Room (2 Adults + 1 Child)",
        "Deluxe Double Room (1 Adult + 1 Child)",
        "Deluxe Double Room with a balcony",
        "Large double room",
        "Double Room - Disability Access",
        "Deluxe Double Room with a balcony and lake view",
        "Deluxe Double Room with bath",
        "Deluxe Double Room with castle/palace view",
        "Deluxe Double Room with shower",
        "Double room with extra bed",
        "Double Room (1 Adult + 1 Child)",
        "Standard Double Room with a balcony",
        "Double Room with a balcony (2 Adults + 1 Child)",
        "Double Room with swimming pool view",
        "Double Room with mountain view",
        "Double Room with garden view",
        "Double Room with a shared bathroom",
        "Double Room with shared toilet",
        "Double Room with patio",
        "Double Room with private external bathroom",
        "Double Room with a terrace",
        "Double Room with lake view",
        "Budget Double Room",
        "Deluxe Queen Room",
        "Deluxe King Room",
        "King Room with a balcony",
        "King Room with lake view",
        "King Room with garden view",
        "King Room with hydro-massage bath",
        "King Room - Disability Access",
        "Queen Room with garden view",
        "Queen Room with hydro-massage bath",
        "King Room",
        "King Room with pool view",
        "King Room with mountain view",
        "Queen Room",
        "Queen Room - Disability Access",
        "Queen Room with a balcony",
        "Queen Room with swimming pool view",
        "Standard Double Room",
        "Standard King Room",
        "Standard Queen Room",
        "Superior Double Room",
        "Superior King Room",
        "Superior Queen Room",
        "Premium Plus Double Room",
        "Double Room \"Comfort\"",
        "Entrepreneurial Deluxe Room",
        "Business Room",
        "Deluxe Double +",

    ],
    ("Triple room", 3): [
        "Triple room - Disability Access",
        "Budget Triple Room",
        "Executive Triple Room",
        "Standard Triple Room",
        "Standard Triple Room with beachfront",
        "Comfort Triple Room",
        "Comfort Triple Room with shower",
        "Deluxe Triple Room",
        "Deluxe Triple Room with beachfront",
        "Triple room with a balcony",
        "Triple room with bathroom",
        "Triple Room with swimming pool view",
        "Triple Room with city view",
        "Triple Room with mountain view",
        "Triple Room with lake View",
        "Triple Room with garden view",
        "Triple room with shared bathroom",
        "Triple room with shared restroom",
        "Triple room without windows",
        "Triple Room with Private External Bathroom",
        "Triple room with a terrace",
        "Superior Triple Room",
        "Superior Triple Room with beachfront",
        "Triple room + folding sofa-bed",

    ],
    ("Cottage", 12): [
        "Quadruple cottage",
        "Three-Bedroom Cottage",
        "Six-bed Cottage",
        "Ten-bed Cottage",
        "Twelve-bed Cottage",
        "Twin-bed Cottage",
        "Family Suite Cottage",
        "Triple cottage",
    ],
    ("Studio room", 1): [
        "Studio - Split Level",
        "Studio - Disability Access",
        "Deluxe Studio",
        "Deluxe King Studio",
        "Deluxe Queen Studio",
        "Studio with a balcony",
        "Studio with pool view",
        "Studio with mountain view",
        "Studio with beachfront",
        "Studio with lake view",
        "Studio with garden view",
        "Studio with Jacuzzi",
        "King Studio",
        "Queen Studio",
        "Studio with a terrace",
        "Family Studio",
        "Triple Studio",
        "Superior Studio",
        "Studio",
    ],
    ("Double or Twin Room", 3): [
        "Large Double or Twin Room",
        "Budget Double or Twin Room",
        "Deluxe Double or Twin Room",
        "Deluxe Double or Twin Room with balcony",
        "Deluxe Double or Twin Room with swimming pool view",
        "Deluxe Double or Twin Room with beachfront",
        "Deluxe Double or Twin Room with river view",
        "Deluxe Double or Twin Room with hydromassage bath",
        "Deluxe Double or Twin Room with city view",
        "Deluxe Double or Twin Room with mountain view",
        "Deluxe Double or Twin Room with lake view",
        "Deluxe Double or Twin Room with garden view",
        "Deluxe Double or Twin Room with pool access",
        "Standard Double or Twin Room",
        "Double or Twin Room - Disability Access",
        "Double or Twin Room with pool view",
        "Double or Twin Room with city view",
        "Double or Twin Room with beachfront",
        "Double or Twin Room with Spa Access",
        "Double or Twin Room with Extra Bed",
        "Double or Twin Room with shower",
        "Double or Twin Room with shared bathroom",
        "Double or Twin Room with private external bathroom",
        "Double or Twin Room with a terrace",
        "Double or Twin Room with mountain view",
        "Double or Twin Room with lake view",
        "Double or Twin Room with garden view",
        "Small Double or Twin Room",
        "Superior Double or Twin Room",
        "Superior Double or Twin Room with city view",
        "Superior Double or Twin Room with beachfront",
        "Superior Double or Twin Room with lake view",
        "Superior Double or Twin Room with garden view",
        "Superior Double or Twin Room with Terrace",
        "Superior Double or Twin Room with pool view",
        "Superior Double or Twin Room with Mountain View",
        "Deluxe Double or Twin Room with city landmarks view",
        "Double or Twin \"Comfort\" room",
        "Double and Twin Economy room",
    ],
    ("Twin room", 2): [
        "Large Twin Room",
        "Budget Twin Room",
        "Deluxe Twin Room with Two Double Beds",
        "Deluxe Twin Room",
        "Twin room with two double beds",
        "Standard Twin room",
        "Twin Room - Disability Access",
        "Twin Room with Balcony",
        "Twin Room with private bathroom",
        "Twin Room with pool view",
        "Twin Room with city view",
        "Twin Room with mountain view",
        "Twin Room with lake view",
        "Twin room with extra bed",
        "Twin room with shower",
        "Twin Room with shared bathroom",
        "Twin room with shared toilet",
        "Twin Room without windows",
        "Twin Room with private external bathroom",
        "Twin Room with a terrace",
        "Twin Room with garden view",
        "Small Twin Room",
        "Superior Twin Room with two double beds",
        "Superior Twin Room",
        "Superior Twin Room with city view",
        "Superior Twin Room with garden view",
        "Superior Twin Room with sauna",
        "Superior Room with two queen beds",
        "Twin room with two rooms",
        "Standard Premium Twin",
        "Standard Premium Twin +",
    ],
    ("Suite", 4): [
        "Suite with balcony",
        "One-bedroom Suite",
        "Two-bedroom suite",
        "Suite room with twin beds",
        "Suite room with a terrace",
        "Super Suite",
        "Double Suite",
        "Triple Suite",
        "Suite",
        "Single Suite",
        "Twin Suite",
        "Grand Suite",
        "Suite with two rooms",
        "Suite \"East\" with two rooms",
        "VIP room",
        "Comfort Suite",
        "Suite \"Panorama\"",
        "Suite with \"king-size\" bed",
        "\"Sultan\" Suite",
        "Presidential Suite",
        "Executive Suite",
        "Business Suite",
        "Couples Suite",
        "Luxury Suite",
        "Quadruple Suite",
        "Family Suite",
        "Suite with garden view",
        "Premium-suite",
        "Family Suite",
    ],
    ("Junior Suite room", 2): [
        "Double Junior Suite",
        "Twin Junior Suite",
        "Single Junior Suite",
        "Triple Junior Suite",
        "Quadruple Junior Suite",
        "Double or Twin Junior Suite",
        "Junior Suite with a \"king-size\" bed with a balcony",
    ],
    ("Yurt", 5): [
        "Yurt",
        "Triple \"Yurt\"",
        "Double/Twin Yurt",
        "Suite Yurt",
        "Suite Yurt \"EMIR\"",
    ],
    ("Bungalow", 4): [
        "Bungalow"
    ],
    ("Conference Hall", 20): [
        "Conference Hall"
    ],
    ("Quintuple room", 5): [
        "Standard Quintuple room",
        "Superior Quintuple room",
        "\"Comfort\" Quintuple room",

    ],
    ("Chalet", 4): [
        "Two-bedroom Chalet",
        "One-Bedroom Chalet",
        "Chalet",
    ],
    ("Couch", 4): [
        "Couch"
    ],
    ("9-bed Shared room", 9): [],
    ("7-bed Shared room", 7): [],
    ("11-bed Shared room", 11): [],
    ("12-bed Shared room", 12): [],
    ("13-bed shared room for women.", 13): [],
    ("Six-bed Room", 6): [],
}
DATAS = [
    {
        "type": r_type[0],
        "max_number_of_guests": r_type[1],
        "names": ModelData(
            RoomName,
            data=[
                {
                    'name': r_name
                }
                for r_name in _DATAS[r_type]

            ],
            parent_field_name='type_id'
        )
    }
    for r_type in _DATAS
]

model_data = ModelData(
    RoomType,
    data=DATAS,
    check_records=True
)
