from app.models import ServiceCategory, Service
from ._conf import ModelData

_PROPERTY_SERVICES = {
    "Popular services": [
        "Wi-fi",
        "Swimming Pool",
        "Sauna",
        "Conference hall",
        "Non-smoking rooms",
        "Family rooms",
        "Garden",
        "Terrace",
        "Master Card Payment",
        "Visa Card Payment",
        "Smoking rooms",
    ],
    "Technologies": [
        "Business centre",
        "Elevator/Lift",
        "Flat screen TV",
        "Electric vehicle charging station",
    ],
    "Health services": [
        "Hot tub/Jacuzzi",
        "Fitness",
        "Massage",
        "Cosmetology",
        "Spa",
        "Yoga",
        "Massage chair",
        "Children's swimming pool",
        "Hydromassage bath",
        "Sun loungers / beach chairs",
        "Parasols",
        "Steam room",
        "Personal coach",
        "Turkish sauna",
        "Solarium",
        "Onsen",
        "Public baths",

    ],
    "Food and Beverages": [
        "Restaurant",
        "Restaurant (buffet)",
        "Bar",
        "Delivery of products (extra charge)",
        "Vending Machine (drinks)",
        "Vending Machine (snacks)",
        "Diet menus (on request)",
        "Delivery of food to the room",
        "Breakfast delivery to the room (on request)",
        "Snack bar",
        "BBQ facilities",
        "Packed lunches (on request)",
        "On-site coffee shop",
        "Fruits",
        "Menu for kids",
        "National sweets",

    ],
    "Entertainment and family services": [
        "Night club/DJ",
        "New Year show programs",
        "Karaoke",
        "Children's club",
        "Children playground",
        "Children's TV channels",
        "Indoor play area",
        "Board games and/or puzzles",
        "Childcare services",
        "Baby carriage",
        "Evening program",
    ],
    "Sports & Recreation": [
        "Basketball court",
        "Bowling",
        "Tennis court",
        "Billiards",
        "Table tennis",
        "Horseback riding",
        "Equipment for badminton",
        "Beach",
        "Darts",
        "Aquapark",
        "Stand-up comedy",
        "Movie evenings",
        "Cycling",
        "Live sporting events",
    ],
    "Cleaning Services": [
        "Dry-cleaning (extra charge)",
        "Dry-cleaning",
        "Ironing service (extra charge)",
        "Ironing service",
        "Laundry (extra charge)",
        "Laundry",
        "Shoe shine",
        "Daily cleaning",
        "Trouser Press",
    ],
    "Shops": [
        "Shops on site",
        "Mini-market on site",
        "Gift shop",
    ],
    "Miscellaneous": [
        "Smoke-free property",
        "Honeymoon suite",
        "VIP room facilities",
        "Call an ambulance",
        "First aid kit",
        "Animal placement (extra charge)",
        "Pet basket",
        "24 hour security",
        "Smoke detectors",
        "CCTV/Video monitoring outside the building",
        "Fire extinguishers",
        "Hypoallergenic room",
    ],
    "Transport": [
        "Covered parking",
        "Bicycles for rent",
        "Shuttle",
        "Secure parking",
        "Street parking",
        "Taxi ordering",
        "Shuttle (extra charge)",
        "Transfer to the ski slope",
        "Bicycle (free of charge)",
        "Bicycle rental (extra charge)",
        "Car rental",
    ],
    "Reception services": [
        "Fax/photocopying",
        "Concierge service",
        "24-hour front desk",
        "Express check-in/check-out",
        "Private check-in/check-out",
        "Tour desk (extra charge)",
        "Currency exchange",
        "Ticket service",
        "ATM/cash machine on site",
        "Guide service (extra charge)",
        "Parking by staff",
        "Newspapers",
        "Brochures and guides",
        "Baggage storage",
    ],
    "Public Areas": [
        "Swimming place",
        "Designated smoking area",
        "Sun terrace",
        "Shared kitchen",
        "Picnic area",
        "Library",
        "Mosque / Church / Temple",
        "Shared lounge with TV set",
        "Garden furniture",

    ],
}
_ROOM_SERVICES = {
    "Bathroom": [
        "Shower",
        "Bathtub",
        "Hydromassage bath",
        "Shared bathroom and restroom",
        "Bidet",
        "Bathrobe",
        "Slippers",
        "Free toiletries",
        "Restroom",
        "Toilet paper",
        "Hand dryer",
        "Towels",
        "Hair dryer",
        "Toothbrush",
        "Shower cap",
    ],
    "Food and Beverages": [
        "Fridge",
        "Dinette",
        "Dinner table",
        "BBQ facilities",
        "Stove",
        "Toaster",
        "Electric kettle",
        "Mini-bar",
        "Outdoor dining area",
        "Kitchenette",
        "Kitchenware",
        "Microwave",
        "Coffee machine",
        "Bottle of water",
    ],
    "Facilities": [
        "Hardwood/Parquet floors",
        "Clothes hanger",
        "Clothes dryer",
        "Closet/Wardrobe",
        "Folding bed",
        "Carpet covering",
        "Sofa",
        "Extra long beds (over 2 meters)",
        "Fan",
        "Work-table",
        "Fireplace",
        "Heating",
        "Adjacent room",
        "Iron",
        "Ironing board",
        "Mosquito grid",
        "Living room",
        "Toilet with handrail",
        "Elevator/Lift",
        "Stairs",
        "Sofa bed",
        "Trash cans",
        "Private pool",
        "Tile / Marble floor",
        "Pajamas",
        "Outlet near the bed",
    ],
    "Technologies": [
        "Air-conditioning",
        "Computer",
        "Game console",
        "Safe",
        "Soundproofing",
        "Wi-Fi",
        "Telephone",
        "Flat screen TV",
        "Satellite channels",
        "Cable Channels",
    ],
    "Services and additions": [
        "Alarm clock",
        "Wake-up service",
        "Linens",
        "Bed linen (additional charge)",
        "Laundry",
        "Laundry (additional charge)",
        "Cleaning products",
        "Daily cleaning",
        "Login by electronic card",
        "Key entry",
        "Lockers",
        "Balcony",
        "The room is located on the ground floor",
    ],
}
model_data = ModelData(
    ServiceCategory,
    [
        *[
            {
                'category_name': category_name,
                'is_property_service_category': True,
                'services': ModelData(
                    Service,
                    [
                        {
                            'service_name': service_name
                        }
                        for service_name in _PROPERTY_SERVICES[category_name]
                    ],
                    parent_field_name='category_id'
                )
            }
            for category_name in _PROPERTY_SERVICES
        ],
        *[
            {
                'category_name': category_name,
                'is_property_service_category': False,
                'services': ModelData(
                    Service,
                    [
                        {
                            'service_name': service_name
                        }
                        for service_name in _ROOM_SERVICES[category_name]
                    ],
                    parent_field_name='category_id'
                )
            }
            for category_name in _ROOM_SERVICES
        ],

    ],
    check_records=True
)
