"""empty message

Revision ID: 712e8fd1ec49
Revises: 
Create Date: 2023-04-10 11:03:21.841992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '712e8fd1ec49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bed_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_file',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_file_id'), 'doc_file', ['id'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lang_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('chief_id', sa.Integer(), nullable=False),
    sa.Column('default_property_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chief_id')
    )
    op.create_table('merchant_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('max_number_of_guests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_gte', sa.Float(), nullable=False),
    sa.Column('price_lte', sa.Float(), nullable=False),
    sa.Column('property_types', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('city_centre_distances', sa.ARRAY(sa.Float()), server_default='{}', nullable=False),
    sa.Column('star_ratings', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('ratings', sa.ARRAY(sa.Float()), server_default='{}', nullable=False),
    sa.Column('other_filters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('is_property_service_category', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('about_us_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('about_us_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['about_us_id'], ['about_us.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bed_type_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('bed_type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bed_type_id'], ['bed_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_slug', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('photo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['doc_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('firma_type', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('payment_account', sa.String(), nullable=True),
    sa.Column('usd_block', sa.Float(precision=10, decimal_return_scale=2), nullable=True),
    sa.Column('oked', sa.String(), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('mfo', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('okonh', sa.String(), nullable=True),
    sa.Column('based', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['merchant_dashboard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('added_by_id')
    )
    op.create_table('faq_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faq_id'], ['faq.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('lang_name', sa.String(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_topic_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['merchant_topic.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.Column('_password', sa.String(), nullable=True),
    sa.Column('role', postgresql.ENUM('CHIEF', 'MANAGER', name='merchantuserrole'), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('photo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['merchant_dashboard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['doc_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_user_phone'), 'merchant_user', ['phone'], unique=False)
    op.create_table('property_type_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['room_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_type_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_filter_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['saved_filter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_category_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('photo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['doc_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('withdrawal_amount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('amount_unit', postgresql.ENUM('FIXED_VALUE', 'PERCENTAGE_VALUE', name='billingunit'), nullable=False),
    sa.Column('amount_for_resident', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('amount_unit_for_resident', postgresql.ENUM('FIXED_VALUE', 'PERCENTAGE_VALUE', name='billingunit'), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('photo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['doc_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', name='chatsessionstatus'), nullable=False),
    sa.Column('has_new_message', sa.Boolean(), nullable=True),
    sa.Column('last_message_from', postgresql.ENUM('OPERATOR', 'USER', name='chatsessionparticipant'), nullable=True),
    sa.Column('is_problem_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', name='chatsessionstatus'), nullable=False),
    sa.Column('has_new_message', sa.Boolean(), nullable=True),
    sa.Column('last_message_from', postgresql.ENUM('OPERATOR', 'USER', name='chatsessionparticipant'), nullable=True),
    sa.Column('is_problem_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['merchant_topic.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['merchant_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('is_breakfast_served', sa.Boolean(), nullable=False),
    sa.Column('is_breakfast_included_in_price', sa.Boolean(), nullable=False),
    sa.Column('airport_distance', sa.Float(), nullable=True),
    sa.Column('city_centre_distance', sa.Float(), nullable=False),
    sa.Column('railway_distance', sa.Float(), nullable=True),
    sa.Column('star_rating', postgresql.ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='propertystarrating'), nullable=False),
    sa.Column('total_number_of_rooms', sa.Integer(), nullable=False),
    sa.Column('minimum_price_per_night', sa.Float(precision=10, decimal_return_scale=2), nullable=True),
    sa.Column('minimum_price_per_night_for_resident', sa.Float(precision=10, decimal_return_scale=2), nullable=True),
    sa.Column('checkin_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkin_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkout_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkout_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', postgresql.ENUM('PENDING', 'ACTIVE', 'IN_ACTIVE', name='propertystatus'), nullable=False),
    sa.Column('pets_allowed', sa.Boolean(), nullable=False),
    sa.Column('smoking_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['merchant_dashboard.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['property_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_name_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('room_name_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_name_id'], ['room_name.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('social_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('social_type', postgresql.ENUM('FACEBOOK', 'GOOGLE', name='socialtype'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_account_social_id'), 'social_account', ['social_id'], unique=True)
    op.create_table('article_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('booked_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('total_number_of_people', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'ACTIVE', 'CLOSED', 'CANCELED', name='bookingstatus'), nullable=False),
    sa.Column('is_arrived', sa.Boolean(), nullable=False),
    sa.Column('reason_of_cancellation', sa.Text(), nullable=True),
    sa.Column('canceled_by', sa.Enum('CLIENT', 'MERCHANT_USER', name='bookingcanceledby'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('from_whom', postgresql.ENUM('OPERATOR', 'USER', name='chatsessionparticipant'), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('from_whom', postgresql.ENUM('OPERATOR', 'USER', name='chatsessionparticipant'), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['merchant_chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['doc_file.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_review_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('short_text', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_room_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('number_of_rooms', sa.Integer(), nullable=False),
    sa.Column('max_number_of_guests', sa.Integer(), nullable=False),
    sa.Column('max_number_of_children', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('smoking_allowed', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('price_has_discount', sa.Boolean(), nullable=False),
    sa.Column('price_discount_unit', sa.Enum('FIXED_VALUE', 'PERCENTAGE_VALUE', name='billingunit'), nullable=True),
    sa.Column('price_discount_amount', sa.Float(), nullable=False),
    sa.Column('price_discount_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_discount_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_for_resident', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('price_for_resident_has_discount', sa.Boolean(), nullable=False),
    sa.Column('price_for_resident_discount_unit', sa.Enum('FIXED_VALUE', 'PERCENTAGE_VALUE', name='billingunit'), nullable=True),
    sa.Column('price_for_resident_discount_amount', sa.Float(), nullable=False),
    sa.Column('price_for_resident_discount_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_for_resident_discount_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_for_less_people', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_for_resident_less_people', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['name_id'], ['room_name.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['room_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('icon_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['doc_file.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Enum('FOR_SERVICE', 'TOP_UP_THE_BALANCE', name='transactiontitle'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', name='transactionstatus'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('amount', sa.Float(precision=10, decimal_return_scale=2), nullable=True),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['merchant_dashboard.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_rating_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['property_review_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rating_id'], ['property_rating.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_review_question_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='languages'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('short_text', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['property_review_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['property_room_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_question_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['property_review_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bed_type_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('number_of_beds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bed_type_id'], ['bed_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['property_room_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['doc_file.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['property_room_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['property_room_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booked_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('property_room_template_id', sa.Integer(), nullable=False),
    sa.Column('property_room_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'ACTIVE', 'CLOSED', 'CANCELED', name='bookingstatus'), nullable=False),
    sa.Column('number_of_people', sa.Integer(), nullable=False),
    sa.Column('reason_of_cancellation', sa.Text(), nullable=True),
    sa.Column('canceled_by', sa.Enum('CLIENT', 'MERCHANT_USER', name='bookingcanceledby'), nullable=True),
    sa.Column('for_resident', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['property_room_id'], ['property_room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_room_template_id'], ['property_room_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_room_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked_room_id', sa.Integer(), nullable=False),
    sa.Column('bed_for_children', sa.Boolean(), nullable=True),
    sa.Column('bed_type_id', sa.Integer(), nullable=False),
    sa.Column('number_of_beds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bed_type_id'], ['bed_type.id'], ),
    sa.ForeignKeyConstraint(['booked_room_id'], ['booked_room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_room_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('property_room_id', sa.Integer(), nullable=True),
    sa.Column('booked_room_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EMPTY', 'BUSY', 'UNDER_RENOVATION', name='roomstatus'), nullable=True),
    sa.Column('status_from', sa.Date(), nullable=True),
    sa.Column('status_until', sa.Date(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booked_room_id'], ['booked_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_room_id'], ['property_room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_room_status')
    op.drop_table('booked_room_bed')
    op.drop_table('booked_room')
    op.drop_table('user_comment')
    op.drop_table('room_service')
    op.drop_table('room_photo')
    op.drop_table('room_bed')
    op.drop_table('review_question_answer')
    op.drop_table('property_room')
    op.drop_table('property_review_question_translation')
    op.drop_table('property_rating_item')
    op.drop_table('user_favourite')
    op.drop_table('transaction')
    op.drop_table('property_translation')
    op.drop_table('property_service')
    op.drop_table('property_room_template')
    op.drop_table('property_review_question')
    op.drop_table('property_rating')
    op.drop_table('property_photo')
    op.drop_table('property_language')
    op.drop_table('merchant_chat_message')
    op.drop_table('chat_message')
    op.drop_table('booking')
    op.drop_table('article_translation')
    op.drop_index(op.f('ix_social_account_social_id'), table_name='social_account')
    op.drop_table('social_account')
    op.drop_table('service_translation')
    op.drop_table('room_name_translation')
    op.drop_table('property')
    op.drop_table('merchant_chat_session')
    op.drop_table('city_translation')
    op.drop_table('chat_session')
    op.drop_table('article')
    op.drop_table('withdrawal_amount')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_table('topic_translation')
    op.drop_table('service_category_translation')
    op.drop_table('service')
    op.drop_table('saved_filter_translation')
    op.drop_table('room_type_translation')
    op.drop_table('room_name')
    op.drop_table('property_type_translation')
    op.drop_index(op.f('ix_merchant_user_phone'), table_name='merchant_user')
    op.drop_table('merchant_user')
    op.drop_table('merchant_topic_translation')
    op.drop_table('language_translation')
    op.drop_table('faq_translation')
    op.drop_table('contract')
    op.drop_table('city')
    op.drop_table('bed_type_translation')
    op.drop_table('about_us_translation')
    op.drop_table('topic')
    op.drop_table('service_category')
    op.drop_table('saved_filter')
    op.drop_table('room_type')
    op.drop_table('property_type')
    op.drop_table('merchant_topic')
    op.drop_table('merchant_dashboard')
    op.drop_table('language')
    op.drop_table('faq')
    op.drop_index(op.f('ix_doc_file_id'), table_name='doc_file')
    op.drop_table('doc_file')
    op.drop_table('bed_type')
    op.drop_table('about_us')
    # ### end Alembic commands ###
